export const LeftSvg = () => {
	return (
		<svg
			className="absolute -top-[1px] left-[76px] h-9 origin-top-left -skew-x-[30deg] -scale-x-100 overflow-visible md:hidden"
			version="1.1"
			xmlns="http://www.w3.org/2000/svg"
			xmlnsXlink="http://www.w3.org/1999/xlink"
			viewBox="0 0 128 32"
			xmlSpace="preserve"
		>
			<defs>
				<pattern
					id="noisePattern"
					patternUnits="userSpaceOnUse"
					width="200"
					height="200"
				>
					<image
						href="/assets/noise.png"
						x="0"
						y="0"
						width="200"
						height="200"
					/>
				</pattern>
			</defs>
			<line
				stroke="hsl(var(--sidebar-svg))"
				strokeWidth="2px"
				shapeRendering="optimizeQuality"
				vectorEffect="non-scaling-stroke"
				strokeLinecap="round"
				strokeMiterlimit="10"
				x1="1"
				y1="0"
				x2="128"
				y2="0"
			/>
			<path
				className="translate-y-[0.5px]"
				stroke="hsl(var(--page-border))"
				fill="hsl(var(--sidebar-background))"
				shapeRendering="optimizeQuality"
				strokeWidth="1px"
				strokeLinecap="round"
				strokeMiterlimit="10"
				vectorEffect="non-scaling-stroke"
				d="M0,0c5.9,0,10.7,4.8,10.7,10.7v10.7c0,5.9,4.8,10.7,10.7,10.7H128V0"
			/>
			<path
				className="translate-y-[0.5px]"
				fill="url(#noisePattern)"
				shapeRendering="optimizeQuality"
				d="M0,0c5.9,0,10.7,4.8,10.7,10.7v10.7c0,5.9,4.8,10.7,10.7,10.7H128V0"
			/>
		</svg>
	)
}

export const RightSvg = () => {
	return (
		<svg
			className="absolute -right-[70px] -top-[1px] h-9 origin-top-left skew-x-[30deg] overflow-visible"
			version="1.1"
			xmlns="http://www.w3.org/2000/svg"
			xmlnsXlink="http://www.w3.org/1999/xlink"
			viewBox="0 0 128 32"
			xmlSpace="preserve"
		>
			<defs>
				<pattern
					id="noisePattern"
					patternUnits="userSpaceOnUse"
					width="200"
					height="200"
				>
					<image
						href="/assets/noise.png"
						x="0"
						y="0"
						width="200"
						height="200"
					/>
				</pattern>
			</defs>
			<line
				stroke="hsl(var(--sidebar-svg))"
				strokeWidth="2px"
				shapeRendering="optimizeQuality"
				vectorEffect="non-scaling-stroke"
				strokeLinecap="round"
				strokeMiterlimit="10"
				x1="1"
				y1="0"
				x2="128"
				y2="0"
			/>
			<path
				className="translate-y-[0.5px]"
				stroke="hsl(var(--page-border))"
				fill="hsl(var(--sidebar-background))"
				shapeRendering="optimizeQuality"
				strokeWidth="1px"
				strokeLinecap="round"
				strokeMiterlimit="10"
				vectorEffect="non-scaling-stroke"
				d="M0,0c5.9,0,10.7,4.8,10.7,10.7v10.7c0,5.9,4.8,10.7,10.7,10.7H128V0"
			/>
			<path
				className="translate-y-[0.5px]"
				fill="url(#noisePattern)"
				shapeRendering="optimizeQuality"
				d="M0,0c5.9,0,10.7,4.8,10.7,10.7v10.7c0,5.9,4.8,10.7,10.7,10.7H128V0"
			/>
		</svg>
	)
}
